name: Deploy to GCP Compute Engine

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: 22
          script: |
            # Pindah ke folder user
            cd /home/${{ secrets.USERNAME }}

            # TEKNIK BERSIH-BERSIH:
            # Hapus folder lama sepenuhnya agar download benar-benar fresh
            # Ini mengatasi masalah jika download sebelumnya macet/corrupt
            sudo rm -rf project-cloud

            # Clone ulang (Pastikan REPO SUDAH PUBLIC)
            # GANTI USERNAME DAN NAMA REPO DI BAWAH INI:
            git clone https://github.com/rezamaulanastarbhak/ujk_integrator.git project-cloud
            
            # Masuk ke folder
            cd project-cloud

            # Build & Restart Container dengan SUDO
            # Pakai sudo agar tidak kena error "permission denied"
            sudo docker stop web-app || true
            sudo docker rm web-app || true
            
            # Build image baru
            sudo docker build --no-cache -t web-image .
            
            # Jalankan container
            sudo docker run -d --name web-app -p 80:80 web-image